# Generated by Django 4.0.4 on 2022-05-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NG_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ng_groupname', models.CharField(db_index=True, max_length=100)),
                ('ng_start', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NG_Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ng_client', models.CharField(max_length=255)),
                ('ng_tel', models.CharField(max_length=20)),
                ('ng_email', models.CharField(max_length=50)),
                ('ng_predpay', models.BooleanField(default=False)),
                ('ng_pismo', models.BooleanField(default=False)),
                ('ng_balance', models.IntegerField()),
                ('ng_predpay_summ', models.IntegerField()),
                ('ng_comment', models.TextField(blank=True)),
                ('ng_gname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='obuchenie.ng_course')),
            ],
        ),
    ]
