# Generated by Django 4.0.4 on 2022-05-24 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(help_text='имя группы', max_length=255, verbose_name='название группы')),
                ('groupstart', models.DateField(blank=True, help_text='дата начала обучения', null=True, verbose_name='Старт обучения')),
                ('price', models.IntegerField(help_text='стоимость курса', null=True, verbose_name='стоимость курса')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='фио студента', max_length=255)),
                ('tel', models.IntegerField(help_text='номер телефона', max_length=30, verbose_name='телефон')),
                ('email', models.CharField(help_text='эл. почта', max_length=50, null=True)),
                ('predpay', models.BooleanField(default=False, help_text='предоплата', null=True, verbose_name='предоплата')),
                ('infomail', models.BooleanField(default=False, help_text='инф. письмо', null=True, verbose_name='инф. письмо')),
                ('balance', models.IntegerField(help_text='оплачено', null=True, verbose_name='оплачено')),
                ('predpay_summ', models.IntegerField(help_text='предоплата', null=True, verbose_name='предоплата')),
                ('ng_comment', models.TextField(blank=True, null=True)),
                ('groupname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ng_learn.group')),
            ],
        ),
    ]
