# Generated by Django 4.0.4 on 2022-05-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ng_learn', '0002_alter_student_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='otche',
            field=models.CharField(help_text='отчество', max_length=255, null=True),
        ),
    ]
